### PR TITLE
Add Missing Fields for Character Data

### PR DESCRIPTION
**Pull request by anysad**
Add missing character fields for:
* `scale`
* `healthIcon`
* `death`
* `offsets`
* `cameraOffsets`
* `isPixel`
* `danceEvery`
* `flipX`

### CODE REVIEW

**Review by biomseed — CHANGES_REQUESTED** [review]
You should write that the scale option is buggy as of now. You should also label the health icon field as optional, because it is. (Actually, there's more optional values you should label as such)

**Comment by anysad** [comment]
Fair enough, will fix it.

**Comment by anysad** [comment]
@biomseed Done.

**Review by biomseed — CHANGES_REQUESTED** [review]
This is good but you might want to specify that flipX and offsets in the health icon data is optional. There might be more optional fields in the death data so you might want to label those too (unless you knew what you were doing and decided to not label them optional on purpose)

**Review by biomseed — APPROVED** [review]
Good. Now all that's needed is for these changes to be made across the other chapters, but I don't know if we should leave it up to Eric or not.

**Comment by biomseed** [comment]
> 
image

Eric being the one who started this thing in the first place

**Pull request merged**
