### PR TITLE
Fix typo in Scripted Classes guide

### PR DESCRIPTION
**Pull request by NotHyper-474**

### CODE REVIEW

**Comment by NotHyper-474** [comment]
For whatever reason it's showing I also modified line 51 🤷‍♂️ shouldn't matter anyway

**Comment by NotHyper-474** [comment]
I would also fix this but have no idea what this was supposed to be

https://github.com/FunkinCrew/funkin-modding-docs/blob/cc84b23f0e296695223c646a2c6a8f8581271087/src/20-using-hscript/20-02-scripted-classes.md?plain=1#L38

**Comment by EliteMasterEric** [comment]
> I would also fix this but have no idea what this was supposed to be
> 
> https://github.com/FunkinCrew/funkin-modding-docs/blob/cc84b23f0e296695223c646a2c6a8f8581271087/src/20-using-hscript/20-02-scripted-classes.md?plain=1#L38

There are two sets of scripted classes:

- Classes which you can extend in a script with `extends` which automatically get loaded, such as character and stage scripts.
- Classes which you can extend in a script with `extends`, which require using the scripted class `init()` function (not currently documented. This includes things like scripted FlxSprites, which you have to initialize from another script such as a stage script. One case where this is used is Week 7, where TankmanSpriteGroup is a scripted FlxSpriteGroup which is initialized by the Week 7 stage.

Feel free to make a clarification there but otherwise I'll merge this typo fix.

**Comment by NotHyper-474** [comment]
> Feel free to make a clarification there but otherwise I'll merge this typo fix.

No no I get it, I was talking specifically about the "There are also scripted classes are also", the repetition of "are also" doesn't seems right to me.

**Pull request merged**
